name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
        
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build frontend
      run: |
        cd frontend
        DISABLE_ESLINT_PLUGIN=true CI=false npm run build
        
    - name: Verify build
      run: |
        if [ ! -d "frontend/build" ]; then
          echo "Build directory not created. Build may have failed."
          exit 1
        fi
        echo "Build successful! Contents of build directory:"
        ls -la frontend/build
        
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 91.99.60.5
        username: root
        password: Arabin32
        script_stop: true
        script: |
          echo "Starting deployment process..."
          cd /var/www/viber || { echo "Failed to change directory to /var/www/viber"; exit 1; }
          
          echo "Pulling latest code..."
          git pull
          
          # Backend deployment
          echo "Deploying backend..."
          cd backend || { echo "Failed to change directory to backend"; exit 1; }
          source venv/bin/activate || { echo "Failed to activate virtual environment"; exit 1; }
          pip install -r requirements.txt
          flask db upgrade
          
          # Frontend deployment
          echo "Deploying frontend..."
          cd ../frontend || { echo "Failed to change directory to frontend"; exit 1; }
          npm install
          DISABLE_ESLINT_PLUGIN=true CI=false npm run build
          
          # Restart services
          echo "Restarting services..."
          systemctl restart viber-backend
          systemctl restart nginx
          
          echo "Deployment completed successfully!" 