name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose files to server
        uses: appleboy/scp-action@master
        with:
          host: 91.99.60.5
          username: root
          password: Arabin32
          source: "."
          target: "/var/www/viber"
          overwrite: true

      - name: Deploy with docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: 91.99.60.5
          username: root
          password: Arabin32
          script: |
            cd /var/www/viber
            docker-compose down
            docker system prune -f
            docker-compose up -d --build